kind: pipeline
name: docker-chromium

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    recursive: true


  - name: docker
    image: plugins/docker
    settings:
      repo: storezhang/chromium
      dockerfile: ./Dockerfile
      mirror: https://docker.mirrors.ustc.edu.cn
      storage_driver: vfs
      username: storezhang
      password:
        from_secret: docker_password
      auto_tag: true
      force_tag: true
